# Site settings
title: Becky Marie
email: rbarth5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Becky Marie: Web Design and Development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: beckyBarth
github_username:  rbarth

# Build settings
markdown: kramdown
