# Site settings
title: Becky Marie
email: rbarth5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Becky Marie: Digital Marketing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beckymarie.me.com" # the base hostname & protocol for your site
twitter_username: beckyBarth
github_username:  rbarth
gems: [bourbon]

# Build settings
markdown: kramdown
